version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: my_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - uploads:/app/uploads

  front:
    build:
      context: ./front
      dockerfile: dockerfile
    ports:
      - "4200:80"

volumes:
  pgdata:
  uploads:
