version: "3.3"
services:
  front:
    build:
      context: ./front/
      dockerfile: DockerFile
    restart: always
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - API_URL
    networks:
      - internalapp
      - default

  api:
    build:
      context: ./api/
      dockerfile: DockerFile
    restart: always
    ports:
      - 3000:4000
    environment:
      - NODE_ENV=production
      - TYPEORM_HOST=postgres
      - TYPEORM_PORT
      - TYPEORM_USERNAME
      - TYPEORM_PASSWORD
      - JWT_SECRET_KEY
      - TYPEORM_DATABASE
      - SLACK_CLIENT_SECRET
      - API_PORT=4000
    networks:
      - internalapp
      - default

  postgres:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    networks:
      - internalapp

networks:
  internalapp:
    internal: true
