version: '3.8'

services:
  client:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
  
  server:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production

networks:
  default:
    driver: bridge
