version: "3.3"
services:
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:80"
    environment:
      - API_URL=http://api:4000
    networks:
      - internalapp
      - default

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    restart: always
    expose:
      - 4000
    environment:
      - MYSQL_USER
      - MYSQL_HOST=db
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - JWT_SECRET_KEY
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
      - API_PORT=4000
    networks:
      - internalapp
      - default

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internalapp

networks:
  internalapp:
    internal: true