version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env

  # Our Angular Frontend
  front:
    build:
      dockerfile: Dockerfile
      context: ./front
      target: development
    command: npm run start
    volumes:
      - /usr/src/app/front
      - /usr/src/app/front/node_modules
    ports:
      - "4200:4200"
    links:
      - api

