version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"

