version: "3.3"
services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    restart: always
    expose:
      - 4000
    environment:
      - MYSQL_USER
      - MYSQL_HOST=db
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - JWT_SECRET_KEY
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
      - API_PORT=4000
    networks:
      - internalapp
      - default

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    networks:
      - internalapp

networks:
  internalapp:
    internal: true