# Step 1: Build the Angular application
# Use a Node.js image with an Angular CLI installed
FROM node:18-alpine AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the Angular application
RUN npm run build --prod

# Step 2: Serve the application using an Nginx server
# Use an Nginx image
FROM nginx:stable

# Copy the built Angular app from the previous step
COPY --from=build /app/dist/easy-inventory-front/browser/ /usr/share/nginx/html

# Expose port 80
EXPOSE 80

