# client/Dockerfile
FROM node:18-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Construire l'application Angular avec les variables d'environnement
RUN npm run build --prod

FROM nginx:alpine
COPY --from=build /app/dist/easy-inventory-front /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
