# server/Dockerfile
FROM node:18-alpine

# Install dependencies
RUN apk add --no-cache \
    libreoffice \
    && npm install -g @nestjs/cli

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .


# Construire l'application NestJS
RUN npm run build
EXPOSE 3000
CMD ["node", "dist/main.js"]
